[build]
  command = "npm install && npx ng build --configuration production"
  publish = "dist/dynasty-basketball-trader/browser"

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
